from utils import WorkflowPaths, dump_args

assert "sdata_path" in config.keys(), "Argument --sdata_path is required"

paths = WorkflowPaths(config["sdata_path"])

rule all:
    input:
        paths.explorer_experiment,

rule to_spatialdata:
    input:
        paths.raw,
    output:
        paths.sdata_zgroup,
    conda:
        "spatial"
    shell:
        f"""
        sopa read {config["reader"]["name"]} {paths.sdata_path} {paths.raw} {dump_args(config["segmentation"]["args"])}
        """

rule segmentation:
    input:
        paths.sdata_zgroup,
    output:
        directory(paths.polygons),
    conda:
        "spatial"
    shell:
        f"""
        sopa segmentation {config["segmentation"]["name"]} {paths.sdata_path} {dump_args(config["segmentation"]["args"])}
        """

rule explorer:
    input:
        paths.polygons,
    output:
        paths.explorer_experiment,
    conda:
        "spatial"
    shell:
        f"""
        sopa explorer {paths.sdata_path} {paths.explorer_directory} {dump_args(config["explorer"])}
        """