# For parameters details, see this commented example: https://github.com/gustaveroussy/sopa/blob/main/workflow/config/example_commented.yaml
read:
  technology: toy_dataset
  kwargs:
    genes: 500

patchify:
  patch_width_microns: -1
  patch_overlap_microns: 0

segmentation:
  proseg:
    cell_key: auto

aggregate:
  average_intensities: true
  min_transcripts: 5 # [optional] cells whose transcript count is below that this threshold are filtered
  gene_column: "genes"

explorer:
  gene_column: "genes"
  ram_threshold_gb: 4
  pixel_size: 0.1
