# For parameters details, see this commented example: https://github.com/gustaveroussy/sopa/blob/main/workflow/config/example_commented.yaml
read:
  technology: toy_dataset
  kwargs:
    transcript_cell_id_as_merscope: true

patchify:
  patch_width_microns: 400
  patch_overlap_microns: 20

segmentation:
  baysor:
    min_area: 10
    prior_shapes_key: auto

    config:
      data:
        force_2d: true
        min_molecules_per_cell: 10
        x: "x"
        y: "y"
        z: "z"
        gene: "genes"
        min_molecules_per_gene: 0
        min_molecules_per_segment: 3
        confidence_nn_id: 6

      segmentation:
        scale: 3 # typical cell radius in microns
        scale_std: "25%" # cell radius standard deviation
        prior_segmentation_confidence: 1

aggregate:
  aggregate_channels: true
  min_transcripts: 5 # [optional] cells whose transcript count is below that this threshold are filtered

annotation:
  method: fluorescence
  args:
    marker_cell_dict:
      CK: Tumoral cell
      CD3: T cell
      CD20: B cell

explorer:
  ram_threshold_gb: 4
  pixel_size: 0.1
