# For parameters details, see this commented example: https://github.com/gustaveroussy/sopa/blob/main/workflow/config/example_commented.yaml
read:
  technology: merscope

patchify:
  patch_width_pixel: 6000
  patch_overlap_pixel: 150
  patch_width_microns: 1000
  patch_overlap_microns: 20

segmentation:
  cellpose:
    diameter: 60
    channels: [ "DAPI" ]
    flow_threshold: 2
    cellprob_threshold: -6
    min_area: 2000

  baysor:
    min_area: 20

    config:
      data:
        exclude_genes: "Blank*" # genes excluded from the Baysor segmentation
        force_2d: true # if false, uses 3D mode
        min_molecules_per_cell: 10
        x: "x"
        y: "y"
        z: "z"
        gene: "gene"
        min_molecules_per_gene: 0
        min_molecules_per_segment: 3
        confidence_nn_id: 6

      segmentation:
        scale: 6.25 # typical cell radius in microns
        scale_std: "25%" # cell radius standard deviation
        prior_segmentation_confidence: 1 # confidence of the cellpose confidence (float in [0, 1])
        estimate_scale_from_centers: false
        n_clusters: 4
        iters: 500
        n_cells_init: 0
        nuclei_genes: ""
        cyto_genes: ""

aggregate:
  aggregate_channels: true
  min_transcripts: 10 # [optional] cells whose transcript count is below that this threshold are filtered

# Comment this out if you want to use tangram -->

# annotation:
#   method: tangram
#   args:
#     sc_reference_path: "..."
#     cell_type_key: ct

explorer:
  gene_column: "gene"
  ram_threshold_gb: 4
  pixel_size: 0.108
