# For parameters details, see this commented example: https://github.com/gustaveroussy/sopa/blob/main/workflow/config/example_commented.yaml
read:
  technology: xenium

patchify:
  patch_width_pixel: 6000
  patch_overlap_pixel: 150
  patch_width_microns: 1000
  patch_overlap_microns: 20

segmentation:
  cellpose:
    diameter: 30
    channels: [ "DAPI" ] # among "DAPI", "ATP1A1/CD45/E-Cadherin", "18S", "AlphaSMA/Vimentin"
    flow_threshold: 2
    cellprob_threshold: -6
    min_area: 400

aggregate:
  aggregate_channels: true
  gene_column: "feature_name"
  min_transcripts: 10 # [optional] cells whose transcript count is below that this threshold are filtered

# Comment this out if you want to use tangram -->

# annotation:
#   method: tangram
#   args:
#     sc_reference_path: "..."
#     cell_type_key: ct

explorer:
  gene_column: "feature_name"
  ram_threshold_gb: 4
