# For parameters details, see this commented example: https://github.com/gustaveroussy/sopa/blob/main/workflow/config/example_commented.yaml
read:
  technology: cosmx

patchify:
  patch_width_pixel: 6000
  patch_overlap_pixel: 150
  patch_width_microns: 800
  patch_overlap_microns: 50

segmentation:
  cellpose:
    diameter: 60
    channels: [ "DNA" ]
    flow_threshold: 2
    cellprob_threshold: -6
    min_area: 2000

  comseg:
    min_area: 10
    config:
      dict_scale:
        x: 1
        y: 1
        z: 1
      mean_cell_diameter: 8
      max_cell_radius: 15
      allow_disconnected_polygon: true
      alpha: 0.5
      min_rna_per_cell: 5
      gene_column: "genes"
      norm_vector: false # [optional] requires exeternal R package '"sctransform"' "feather" and "arrow" to be installed, otherwise set to false

aggregate:
  aggregate_channels: true
  min_transcripts: 10 # [optional] cells whose transcript count is below that this threshold are filtered

# Comment this out if you want to use tangram -->

# annotation:
#   method: tangram
#   args:
#     sc_reference_path: "..."
#     cell_type_key: ct

explorer:
  gene_column: "target"
  ram_threshold_gb: 4
