# Using the CosMx default segmentation as a prior for Proseg.

# For parameters details, see this commented example: https://github.com/gustaveroussy/sopa/blob/main/workflow/config/example_commented.yaml
read:
  technology: cosmx

patchify:
  patch_width_microns: -1 # only one patch
  patch_overlap_microns: 0

segmentation:
  proseg:
    prior_shapes_key: auto # this allows to use the prior segmentation performed when using the CosMx
    # command_line_suffix: "--nthreads XXX" # add here any command line suffix to the proseg command

aggregate:
  aggregate_channels: true
  min_transcripts: 10 # [optional] cells whose transcript count is below that this threshold are filtered

explorer:
  ram_threshold_gb: 4
