# For parameters details, see this commented example: https://github.com/gustaveroussy/sopa/blob/main/workflow/config/example_commented.yaml
read:
  technology: ome_tif

patchify:
  patch_width_pixel: 3000
  patch_overlap_pixel: 40

segmentation:
  cellpose:
    diameter: 8
    channels: [ "DAPI" ]
    flow_threshold: 2
    cellprob_threshold: -6
    min_area: 16

aggregate:
  aggregate_channels: true
  min_intensity_ratio: 0.1
  expand_radius_ratio: 0.1

explorer:
  ram_threshold_gb: 4
  pixel_size: 1
